-- Membros verificados do dashboard de DM. Rode UMA vez no Supabase: SQL Editor > New query > Run.
-- Use o MESMO projeto Supabase que a Zoe (o bot) já usa.

create table if not exists members (
  id            bigint generated by default as identity primary key,
  discord_id    text not null unique,
  username      text not null,
  webhook_url   text,
  excluded      boolean not null default false,
  verified_at   timestamptz not null default now()
);
